package minestrapp.crafting;

import minestrapp.MBlocks;
import minestrapp.MItems;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.ItemStack;
import net.minecraftforge.oredict.OreDictionary;

public class OreDictRegistry
{
	public static void register()
	{
		OreDictionary.registerOre("cropBlueberry", MItems.blueberry);
		OreDictionary.registerOre("cropRaspberry", MItems.raspberry);
		OreDictionary.registerOre("cropBlackberry", MItems.blackberry);
		OreDictionary.registerOre("cropStrawberry", MItems.strawberry);
		OreDictionary.registerOre("cropVoidberry", MItems.voidberry);
		OreDictionary.registerOre("cropBerry", MItems.blueberry);
		OreDictionary.registerOre("cropBerry", MItems.raspberry);
		OreDictionary.registerOre("cropBerry", MItems.blackberry);
		OreDictionary.registerOre("cropBerry", MItems.strawberry);
		OreDictionary.registerOre("cropBerry", MItems.voidberry);
		OreDictionary.registerOre("cropPepper", MItems.pepper);
		OreDictionary.registerOre("cropCabbage", MItems.cabbage);
		OreDictionary.registerOre("cropCelery", MItems.celery);
		OreDictionary.registerOre("cropOnion", MItems.onion);
		OreDictionary.registerOre("cropPeanut", MItems.peanuts);
		OreDictionary.registerOre("cropLettuce", MItems.lettuce);
		OreDictionary.registerOre("cropTomato", MItems.tomato);
		OreDictionary.registerOre("cropCorn", MItems.corn);
		OreDictionary.registerOre("moss", MBlocks.moss);
		OreDictionary.registerOre("glowMoss", MBlocks.carpet_glow_moss);
		OreDictionary.registerOre("glowMoss", MBlocks.creeping_glow_moss);
		OreDictionary.registerOre("glowMoss", MBlocks.hanging_glow_moss);
		OreDictionary.registerOre("candle", new ItemStack(MBlocks.candle, 1, OreDictionary.WILDCARD_VALUE));
		OreDictionary.registerOre("sand", new ItemStack(MBlocks.cold_sand, 1, OreDictionary.WILDCARD_VALUE));
		OreDictionary.registerOre("sandNormal", new ItemStack(Blocks.SAND, 1, OreDictionary.WILDCARD_VALUE));
		OreDictionary.registerOre("sandCold", new ItemStack(MBlocks.cold_sand, 1, OreDictionary.WILDCARD_VALUE));
		OreDictionary.registerOre("dirt", MBlocks.clay_soil);
		OreDictionary.registerOre("grass", MBlocks.clay_grass);
		OreDictionary.registerOre("dirt", MBlocks.permafrost);
		OreDictionary.registerOre("grass", MBlocks.lichen);
		OreDictionary.registerOre("dirt", MBlocks.mud);
		OreDictionary.registerOre("dirt", MBlocks.dried_mud);
		OreDictionary.registerOre("soilDry", new ItemStack(Blocks.DIRT, 1, 0));
		OreDictionary.registerOre("soilDry", new ItemStack(Blocks.DIRT, 1, 1));
		OreDictionary.registerOre("soilDry", new ItemStack(MBlocks.clay_soil, 1, 0));
		OreDictionary.registerOre("soilDry", new ItemStack(MBlocks.clay_soil, 1, 1));
		OreDictionary.registerOre("soilDry", MBlocks.dried_mud);
		OreDictionary.registerOre("logWood", new ItemStack(MBlocks.log, 1, OreDictionary.WILDCARD_VALUE));
		OreDictionary.registerOre("plankWood", new ItemStack(MBlocks.planks, 1, OreDictionary.WILDCARD_VALUE));
		OreDictionary.registerOre("plankWood", new ItemStack(MBlocks.mossy_m_planks, 1, OreDictionary.WILDCARD_VALUE));
		OreDictionary.registerOre("slabWood", new ItemStack(MBlocks.wood_slab_1, 1, OreDictionary.WILDCARD_VALUE));
		OreDictionary.registerOre("stairWood", new ItemStack(MBlocks.redwood_plank_stairs, 1, OreDictionary.WILDCARD_VALUE));
		OreDictionary.registerOre("stairWood", new ItemStack(MBlocks.frozen_oak_plank_stairs, 1, OreDictionary.WILDCARD_VALUE));
		OreDictionary.registerOre("stairWood", new ItemStack(MBlocks.charwood_plank_stairs, 1, OreDictionary.WILDCARD_VALUE));
		OreDictionary.registerOre("stone", new ItemStack(MBlocks.stone, 1, OreDictionary.WILDCARD_VALUE));
		OreDictionary.registerOre("cobblestone", new ItemStack(MBlocks.cobblestone, 1, OreDictionary.WILDCARD_VALUE));
		OreDictionary.registerOre("cobblestoneDeep", new ItemStack(MBlocks.cobblestone, 1, 1));
		OreDictionary.registerOre("cobblestoneDeep", new ItemStack(MBlocks.cobblestone, 1, 2));
		OreDictionary.registerOre("cobblestoneDeep", new ItemStack(MBlocks.cobblestone, 1, 4));
		OreDictionary.registerOre("cobblestoneDeep", new ItemStack(MBlocks.cobblestone, 1, 6));
		OreDictionary.registerOre("cobblestoneDeep", new ItemStack(MBlocks.cobblestone, 1, 8));
		OreDictionary.registerOre("bricksStone", new ItemStack(MBlocks.stone_bricks, 1, OreDictionary.WILDCARD_VALUE));
		OreDictionary.registerOre("bricksStone", new ItemStack(MBlocks.cracked_stone_bricks, 1, OreDictionary.WILDCARD_VALUE));
		OreDictionary.registerOre("bricksStone", new ItemStack(MBlocks.mossy_stone_bricks, 1, OreDictionary.WILDCARD_VALUE));
		OreDictionary.registerOre("blockMossy", new ItemStack(MBlocks.mossy_cobblestone, 1, OreDictionary.WILDCARD_VALUE));
		OreDictionary.registerOre("blockMossy", new ItemStack(MBlocks.mossy_stone_bricks, 1, OreDictionary.WILDCARD_VALUE));
		OreDictionary.registerOre("oreSalt", new ItemStack(MBlocks.ore_salt, 1, OreDictionary.WILDCARD_VALUE));
		OreDictionary.registerOre("oreCoal", new ItemStack(MBlocks.ore_coal, 1, OreDictionary.WILDCARD_VALUE));
		OreDictionary.registerOre("oreCopper", new ItemStack(MBlocks.ore_copper, 1, OreDictionary.WILDCARD_VALUE));
		OreDictionary.registerOre("oreTin", new ItemStack(MBlocks.ore_tin, 1, OreDictionary.WILDCARD_VALUE));
		OreDictionary.registerOre("oreIron", new ItemStack(MBlocks.ore_iron, 1, OreDictionary.WILDCARD_VALUE));
		OreDictionary.registerOre("oreGold", new ItemStack(MBlocks.ore_gold, 1, OreDictionary.WILDCARD_VALUE));
		OreDictionary.registerOre("oreRedstone", new ItemStack(MBlocks.ore_redstone, 1, OreDictionary.WILDCARD_VALUE));
		OreDictionary.registerOre("oreLapis", new ItemStack(MBlocks.ore_lapis, 1, OreDictionary.WILDCARD_VALUE));
		OreDictionary.registerOre("oreMeurodite", new ItemStack(MBlocks.ore_meurodite, 1, OreDictionary.WILDCARD_VALUE));
		OreDictionary.registerOre("oreIrradium", new ItemStack(MBlocks.ore_irradium, 1, OreDictionary.WILDCARD_VALUE));
		OreDictionary.registerOre("oreTorite", new ItemStack(MBlocks.ore_torite, 1, OreDictionary.WILDCARD_VALUE));
		OreDictionary.registerOre("oreDiamond", new ItemStack(MBlocks.ore_diamond, 1, OreDictionary.WILDCARD_VALUE));
		OreDictionary.registerOre("oreEmerald", new ItemStack(MBlocks.ore_emerald, 1, OreDictionary.WILDCARD_VALUE));
		OreDictionary.registerOre("oreArchantine", new ItemStack(MBlocks.ore_titanium, 1, OreDictionary.WILDCARD_VALUE));
		OreDictionary.registerOre("oreBlazium", new ItemStack(MBlocks.ore_blazium));
		OreDictionary.registerOre("oreSoul", new ItemStack(MBlocks.ore_soul));
		OreDictionary.registerOre("oreDimensium", new ItemStack(MBlocks.ore_dimensium));
		OreDictionary.registerOre("blockSunstone", MBlocks.block_sunstone);
		OreDictionary.registerOre("blockSalt", MBlocks.block_salt);
		OreDictionary.registerOre("blockRockCrystal", MBlocks.block_rock_crystal);
		OreDictionary.registerOre("blockQuartz", MBlocks.desert_quartz);
		OreDictionary.registerOre("blockQuartz", MBlocks.irradiant_quartz);
		OreDictionary.registerOre("blockDesertQuartz", new ItemStack(MBlocks.desert_quartz, 1, OreDictionary.WILDCARD_VALUE));
		OreDictionary.registerOre("blockIrradiantQuartz", new ItemStack(MBlocks.irradiant_quartz, 1, OreDictionary.WILDCARD_VALUE));
		OreDictionary.registerOre("blockCopper", MBlocks.block_copper);
		OreDictionary.registerOre("blockTin", MBlocks.block_tin);
		OreDictionary.registerOre("blockBronze", MBlocks.block_bronze);
		OreDictionary.registerOre("blockSteel", MBlocks.block_steel);
		OreDictionary.registerOre("blockMeurodite", MBlocks.block_meurodite);
		OreDictionary.registerOre("blockTorite", MBlocks.block_torite);
		OreDictionary.registerOre("blockIrradium", MBlocks.block_irradium);
		OreDictionary.registerOre("blockGlacierite", MBlocks.block_glacierite);
		OreDictionary.registerOre("blockArchantine", MBlocks.block_titanium);
		OreDictionary.registerOre("blockBlazium", MBlocks.block_blazium);
		OreDictionary.registerOre("blockSoulGem", MBlocks.block_soul);
		OreDictionary.registerOre("blockDimensium", MBlocks.block_dimensium);
		OreDictionary.registerOre("blockRedstone", MBlocks.block_redstone_briny_lit);
		OreDictionary.registerOre("blockRedstone", MBlocks.block_redstone_sandy_lit);
		OreDictionary.registerOre("blockRedstone", MBlocks.block_redstone_frosted_lit);
		OreDictionary.registerOre("blockRedstone", MBlocks.block_redstone_icy_lit);
		OreDictionary.registerOre("dustRedstone", MBlocks.redstone_sandy);
		OreDictionary.registerOre("dustRedstone", MBlocks.redstone_frosted);
		OreDictionary.registerOre("dustRedstone", MBlocks.redstone_icy);
		OreDictionary.registerOre("dustRedstone", MBlocks.redstone_briny);
		OreDictionary.registerOre("stickWood", MItems.charroot);
		OreDictionary.registerOre("dustWood", MItems.sawdust);
		OreDictionary.registerOre("dustCopper", new ItemStack(MItems.chunks, 1, 7));
		OreDictionary.registerOre("dustTin", new ItemStack(MItems.chunks, 1, 8));
		OreDictionary.registerOre("dustIron", new ItemStack(MItems.chunks, 1, 9));
		OreDictionary.registerOre("dustGold", new ItemStack(MItems.chunks, 1, 10));
		OreDictionary.registerOre("dustTorite", new ItemStack(MItems.chunks, 1, 11));
		OreDictionary.registerOre("dustArchantine", new ItemStack(MItems.chunks, 1, 12));
		OreDictionary.registerOre("dustDimensium", new ItemStack(MItems.chunks, 1, 13));
		OreDictionary.registerOre("dustIrradium", MItems.irradium);
		OreDictionary.registerOre("nuggetCopper", new ItemStack(MItems.nuggets, 1, 0));
		OreDictionary.registerOre("nuggetTin", new ItemStack(MItems.nuggets, 1, 1));
		OreDictionary.registerOre("nuggetBronze", new ItemStack(MItems.nuggets, 1, 2));
		OreDictionary.registerOre("nuggetSteel", new ItemStack(MItems.nuggets, 1, 3));
		OreDictionary.registerOre("nuggetTorite", new ItemStack(MItems.nuggets, 1, 4));
		OreDictionary.registerOre("nuggetArchantine", new ItemStack(MItems.nuggets, 1, 7));
		OreDictionary.registerOre("nuggetGlacierite", new ItemStack(MItems.nuggets, 1, 5));
		OreDictionary.registerOre("nuggetBlazium", new ItemStack(MItems.nuggets, 1, 6));
		OreDictionary.registerOre("nuggetDimensium", new ItemStack(MItems.nuggets, 1, 8));
		OreDictionary.registerOre("ingotCopper", new ItemStack(MItems.ingots, 1, 0));
		OreDictionary.registerOre("ingotTin", new ItemStack(MItems.ingots, 1, 1));
		OreDictionary.registerOre("ingotBronze", new ItemStack(MItems.ingots, 1, 2));
		OreDictionary.registerOre("ingotSteel", new ItemStack(MItems.ingots, 1, 3));
		OreDictionary.registerOre("ingotTorite", new ItemStack(MItems.ingots, 1, 4));
		OreDictionary.registerOre("ingotArchantine", new ItemStack(MItems.ingots, 1, 5));
		OreDictionary.registerOre("ingotGlacierite", new ItemStack(MItems.ingots, 1, 6));
		OreDictionary.registerOre("ingotBlazium", new ItemStack(MItems.ingots, 1, 7));
		OreDictionary.registerOre("ingotDimensium", new ItemStack(MItems.ingots, 1, 8));
		OreDictionary.registerOre("gemSalt", new ItemStack(MItems.salt));
		OreDictionary.registerOre("gemSunstone", new ItemStack(MItems.gems, 1, 0));
		OreDictionary.registerOre("gemQuartz", new ItemStack(MItems.gems, 1, 1));
		OreDictionary.registerOre("gemDesertQuartz", new ItemStack(MItems.gems, 1, 1));
		OreDictionary.registerOre("gemCrystal", new ItemStack(MItems.gems, 1, 2));
		OreDictionary.registerOre("gemQuartz", new ItemStack(MItems.gems, 1, 3));
		OreDictionary.registerOre("gemIrradiantQuartz", new ItemStack(MItems.gems, 1, 3));
		OreDictionary.registerOre("gemMeurodite", new ItemStack(MItems.gems, 1, 4));
		OreDictionary.registerOre("gemBlazium", new ItemStack(MItems.gems, 1, 5));
		OreDictionary.registerOre("gemGlacierite", new ItemStack(MItems.gems, 1, 6));
		OreDictionary.registerOre("gemSoul", MItems.gem_soul);
		OreDictionary.registerOre("plateTin", new ItemStack(MItems.plating, 1, 0));
		OreDictionary.registerOre("plateBronze", new ItemStack(MItems.plating, 1, 1));
		OreDictionary.registerOre("plateSteel", new ItemStack(MItems.plating, 1, 2));
		OreDictionary.registerOre("plateMeurodite", new ItemStack(MItems.plating, 1, 3));
		OreDictionary.registerOre("plateCopper", new ItemStack(MItems.plating, 1, 4));
		OreDictionary.registerOre("plateGold", new ItemStack(MItems.plating, 1, 5));
		OreDictionary.registerOre("plateIron", new ItemStack(MItems.plating, 1, 6));
		OreDictionary.registerOre("plateTorite", new ItemStack(MItems.plating, 1, 7));
		OreDictionary.registerOre("plateGlacierite", new ItemStack(MItems.plating, 1, 8));
		OreDictionary.registerOre("plateBlazium", new ItemStack(MItems.plating, 1, 9));
		OreDictionary.registerOre("plateDiamond", new ItemStack(MItems.plating, 1, 10));
		OreDictionary.registerOre("plateArchantine", new ItemStack(MItems.plating, 1, 11));
		OreDictionary.registerOre("plateDimensium", new ItemStack(MItems.plating, 1, 12));
		OreDictionary.registerOre("magnet", new ItemStack(MItems.tech_components, 1, 6));
		OreDictionary.registerOre("seedPepper", MItems.pepper_seeds);
		OreDictionary.registerOre("seedCabbage", MItems.cabbage_seeds);
		OreDictionary.registerOre("seedCelery", MItems.celery_seeds);
		OreDictionary.registerOre("seedTomato", MItems.tomato_seeds);
		OreDictionary.registerOre("tallow", new ItemStack(MItems.mob_loot, 1, 1));
		OreDictionary.registerOre("saladGreens", Items.CARROT);
		OreDictionary.registerOre("saladGreens", MItems.pepper);
		OreDictionary.registerOre("saladGreens", MItems.celery);
		OreDictionary.registerOre("saladGreens", MItems.onion);
		OreDictionary.registerOre("saladGreens", MItems.tomato);
		OreDictionary.registerOre("coleslawGreens", MItems.onion);
		OreDictionary.registerOre("coleslawGreens", MItems.pepper);
		OreDictionary.registerOre("leatherBotched", new ItemStack(MItems.leather, 1, 11));
		OreDictionary.registerOre("leatherBotched", new ItemStack(MItems.leather, 1, 12));
		OreDictionary.registerOre("leatherBotched", new ItemStack(MItems.leather, 1, 13));
		OreDictionary.registerOre("leatherBotched", new ItemStack(MItems.leather, 1, 14));
		OreDictionary.registerOre("leatherBotched", new ItemStack(MItems.leather2, 1, 8));
		OreDictionary.registerOre("leatherBotched", new ItemStack(MItems.leather2, 1, 9));
		OreDictionary.registerOre("leatherSuede", new ItemStack(MItems.leather, 1, 12));
		OreDictionary.registerOre("leatherSuede", new ItemStack(MItems.leather, 1, 13));
		OreDictionary.registerOre("leatherSuede", new ItemStack(MItems.leather, 1, 14));
		OreDictionary.registerOre("leatherSuede", new ItemStack(MItems.leather2, 1, 8));
		OreDictionary.registerOre("leatherSuede", new ItemStack(MItems.leather2, 1, 9));
		OreDictionary.registerOre("leatherNormal", new ItemStack(MItems.leather, 1, 13));
		OreDictionary.registerOre("leatherNormal", new ItemStack(MItems.leather, 1, 14));
		OreDictionary.registerOre("leatherNormal", new ItemStack(MItems.leather2, 1, 8));
		OreDictionary.registerOre("leatherNormal", new ItemStack(MItems.leather2, 1, 9));
		OreDictionary.registerOre("leatherFine", new ItemStack(MItems.leather, 1, 14));
		OreDictionary.registerOre("leatherFine", new ItemStack(MItems.leather2, 1, 8));
		OreDictionary.registerOre("leatherFine", new ItemStack(MItems.leather2, 1, 9));
		OreDictionary.registerOre("leatherMystic", new ItemStack(MItems.leather2, 1, 8));
		OreDictionary.registerOre("leatherMystic", new ItemStack(MItems.leather2, 1, 9));
		OreDictionary.registerOre("leatherLegendary", new ItemStack(MItems.leather2, 1, 9));	
		OreDictionary.registerOre("tanninPoor", new ItemStack(Items.CARROT));
		OreDictionary.registerOre("tanninPoor", new ItemStack(Items.MELON));
		OreDictionary.registerOre("tanninPoor", new ItemStack(Items.WHEAT));
		OreDictionary.registerOre("tanninPoor", new ItemStack(Items.DYE, 1, 2));
		OreDictionary.registerOre("tanninPoor", new ItemStack(Items.DYE, 1, 3));
		OreDictionary.registerOre("tanninPoor", new ItemStack(MItems.blackberry));
		OreDictionary.registerOre("tanninPoor", new ItemStack(MItems.strawberry));
		OreDictionary.registerOre("tanninPoor", new ItemStack(MItems.raspberry));
		OreDictionary.registerOre("tanninPoor", new ItemStack(MItems.blueberry));
		OreDictionary.registerOre("tanninPoor", new ItemStack(MItems.cabbage));
		OreDictionary.registerOre("tanninPoor", new ItemStack(MItems.lettuce));
		OreDictionary.registerOre("tanninPoor", new ItemStack(MItems.corn));
		OreDictionary.registerOre("tanninPoor", new ItemStack(MItems.natural_ingredients, 1, OreDictionary.WILDCARD_VALUE));
		OreDictionary.registerOre("tanninPoor", new ItemStack(MItems.tomato));
		OreDictionary.registerOre("tanninPoor", new ItemStack(Items.REEDS));
		OreDictionary.registerOre("tanninNormal", new ItemStack(Items.POTATO));
		OreDictionary.registerOre("tanninNormal", new ItemStack(Items.APPLE));
		OreDictionary.registerOre("tanninNormal", new ItemStack(Items.BEETROOT));
		OreDictionary.registerOre("tanninNormal", new ItemStack(Items.SUGAR));
		OreDictionary.registerOre("tanninNormal", new ItemStack(Items.DYE, 1, 1));
		OreDictionary.registerOre("tanninNormal", new ItemStack(MItems.celery));
		OreDictionary.registerOre("tanninNormal", new ItemStack(MItems.pepper));
		OreDictionary.registerOre("tanninNormal", new ItemStack(MItems.corn_meal));
		OreDictionary.registerOre("tanninNormal", new ItemStack(MItems.onion));
		OreDictionary.registerOre("tanninNormal", new ItemStack(MItems.dough));
		OreDictionary.registerOre("tanninFine", new ItemStack(Items.POISONOUS_POTATO));
		OreDictionary.registerOre("tanninNormal", new ItemStack(MItems.peanuts));
		OreDictionary.registerOre("tanninFine", new ItemStack(MItems.sawdust));
		OreDictionary.registerOre("tanninFine", new ItemStack(MItems.bark));
		OreDictionary.registerOre("skull", new ItemStack(MBlocks.skull_bat));
		OreDictionary.registerOre("skull", new ItemStack(MBlocks.skull_parrot));
		OreDictionary.registerOre("skull", new ItemStack(MBlocks.skull_chicken));
		OreDictionary.registerOre("skull", new ItemStack(MBlocks.skull_rabbit));
		OreDictionary.registerOre("skull", new ItemStack(MBlocks.skull_pig));
		OreDictionary.registerOre("skull", new ItemStack(MBlocks.skull_sheep));
		OreDictionary.registerOre("skull", new ItemStack(MBlocks.skull_cow));
		OreDictionary.registerOre("skull", new ItemStack(MBlocks.skull_llama));
		OreDictionary.registerOre("skull", new ItemStack(MBlocks.skull_horse));
		OreDictionary.registerOre("skull", new ItemStack(MBlocks.skull_ocelot));
		OreDictionary.registerOre("skull", new ItemStack(MBlocks.skull_wolf));
		OreDictionary.registerOre("skull", new ItemStack(MBlocks.skull_polar_bear));
		OreDictionary.registerOre("skull", new ItemStack(MBlocks.skull_squid));
		OreDictionary.registerOre("skull", new ItemStack(MBlocks.skull_villager));
		OreDictionary.registerOre("skull", new ItemStack(Items.SKULL, 1, 0));
		OreDictionary.registerOre("skull", new ItemStack(MBlocks.skull_husk));
		OreDictionary.registerOre("skull", new ItemStack(MBlocks.skull_stray));
		OreDictionary.registerOre("skull", new ItemStack(MBlocks.skull_creeper));
		OreDictionary.registerOre("skull", new ItemStack(MBlocks.skull_guardian));
		OreDictionary.registerOre("skull", new ItemStack(MBlocks.skull_enderman));
		OreDictionary.registerOre("skull", new ItemStack(MBlocks.skull_shulker));
		OreDictionary.registerOre("blockGlassColorless", new ItemStack(MBlocks.glass_tiles));
		OreDictionary.registerOre("blockGlassColorless", new ItemStack(MBlocks.glass_bricks));
		OreDictionary.registerOre("paneGlassColorless", new ItemStack(MBlocks.glass_tile_pane));
		OreDictionary.registerOre("paneGlassColorless", new ItemStack(MBlocks.glass_brick_pane));
		OreDictionary.registerOre("foodDough", MItems.dough);
		OreDictionary.registerOre("foodTortilla", MItems.tortilla);
		OreDictionary.registerOre("foodBun", MItems.bun);
		OreDictionary.registerOre("foodTortillachips", MItems.tortilla_chips);
		OreDictionary.registerOre("foodNachos", MItems.nachos);
		OreDictionary.registerOre("foodCheese", MItems.cheese);
		OreDictionary.registerOre("foodFriedegg", MItems.fried_egg);
		OreDictionary.registerOre("foodFriedegg", MItems.bread_fried_egg);
		OreDictionary.registerOre("foodCalamari", MItems.calamari);
		OreDictionary.registerOre("foodFriedcod", MItems.fried_fish);
		OreDictionary.registerOre("foodBacon", MItems.bacon);
		OreDictionary.registerOre("foodTomatosauce", MItems.tomato_sauce);
		OreDictionary.registerOre("foodTomatosauce", MItems.bread_tomato_sauce);
		OreDictionary.registerOre("foodSalsa", MItems.salsa);
		OreDictionary.registerOre("foodSalsa", MItems.bread_salsa);
		OreDictionary.registerOre("bottleHotsauce", MItems.hot_sauce);
		OreDictionary.registerOre("sandstone",   new ItemStack(MBlocks.sandstone, 1, 2));
		OreDictionary.registerOre("sandstone",   new ItemStack(MBlocks.sandstone, 1, 3));
		OreDictionary.registerOre("sandstone",   new ItemStack(MBlocks.sandstone, 1, 4));
		OreDictionary.registerOre("sandstone",   new ItemStack(MBlocks.sandstone, 1, 6));
		OreDictionary.registerOre("sandstone",   new ItemStack(MBlocks.sandstone, 1, 7));
		OreDictionary.registerOre("sandstone",   new ItemStack(MBlocks.sandstone, 1, 8));
		OreDictionary.registerOre("cold_sandstone",   new ItemStack(MBlocks.sandstone, 1, 2));
		OreDictionary.registerOre("cold_sandstone",   new ItemStack(MBlocks.sandstone, 1, 3));
		OreDictionary.registerOre("cold_sandstone",   new ItemStack(MBlocks.sandstone, 1, 4));
		OreDictionary.registerOre("cold_red_sandstone",   new ItemStack(MBlocks.sandstone, 1, 6));
		OreDictionary.registerOre("cold_red_sandstone",   new ItemStack(MBlocks.sandstone, 1, 7));
		OreDictionary.registerOre("cold_red_sandstone",   new ItemStack(MBlocks.sandstone, 1, 8));
	}
}
